[package]
org = "kasthuriraajan"
name = "azure_sql_sample"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./javalibs/mssql-jdbc-9.2.0.jre11.jar"
