[package]
org = "kasthuriraajan"
name = "azure_mysql_sample"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "./javalibs/mysql-connector-java-8.0.22.jar"
